// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import Dropdown from '@stimulus-components/dropdown'
import ScrollTo from '@stimulus-components/scroll-to'
import HelloController from "./hello_controller"
import AutoSubmit from '@stimulus-components/auto-submit'
import PasswordVisibility from '@stimulus-components/password-visibility'
application.register("hello", HelloController)
application.register("dropdown", Dropdown)
application.register('scroll-to', ScrollTo)
application.register('auto-submit', AutoSubmit)
application.register('password-visibility', PasswordVisibility)
