# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: medical_record_management
services:
  postgresql:
    image: postgres:17.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-medical_record_management}
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $${POSTGRES_USER:-medical_record_management}']
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 127.0.0.1:5432:5432
