# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: medical_record_management
services:
  redis:
    image: redis:7.2.5
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - 127.0.0.1:6379:6379
