# This configuration is intended for development purpose, it's **your** responsibility to harden it for production
name: medical_record_management
services:
  redis:
    extends:
      file: ./redis.yml
      service: redis
  postgresql:
    extends:
      file: ./postgresql.yml
      service: postgresql