require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/coherts", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Cohert. As you add validations to Cohert, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cohert.create! valid_attributes
      get admins_coherts_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cohert = Cohert.create! valid_attributes
      get admins_cohert_url(cohert)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admins_cohert_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cohert = Cohert.create! valid_attributes
      get edit_admins_cohert_url(cohert)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cohert" do
        expect {
          post admins_coherts_url, params: { cohert: valid_attributes }
        }.to change(Cohert, :count).by(1)
      end

      it "redirects to the created cohert" do
        post admins_coherts_url, params: { cohert: valid_attributes }
        expect(response).to redirect_to(admins_cohert_url(Cohert.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cohert" do
        expect {
          post admins_coherts_url, params: { cohert: invalid_attributes }
        }.to change(Cohert, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admins_coherts_url, params: { cohert: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cohert" do
        cohert = Cohert.create! valid_attributes
        patch admins_cohert_url(cohert), params: { cohert: new_attributes }
        cohert.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cohert" do
        cohert = Cohert.create! valid_attributes
        patch admins_cohert_url(cohert), params: { cohert: new_attributes }
        cohert.reload
        expect(response).to redirect_to(cohert_url(cohert))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cohert = Cohert.create! valid_attributes
        patch admins_cohert_url(cohert), params: { cohert: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cohert" do
      cohert = Cohert.create! valid_attributes
      expect {
        delete admins_cohert_url(cohert)
      }.to change(Cohert, :count).by(-1)
    end

    it "redirects to the coherts list" do
      cohert = Cohert.create! valid_attributes
      delete admins_cohert_url(cohert)
      expect(response).to redirect_to(admins_coherts_url)
    end
  end
end
