require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/newsletter_subscriptions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # NewsletterSubscription. As you add validations to NewsletterSubscription, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      NewsletterSubscription.create! valid_attributes
      get admins_newsletter_subscriptions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      newsletter_subscription = NewsletterSubscription.create! valid_attributes
      get admins_newsletter_subscription_url(newsletter_subscription)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_admins_newsletter_subscription_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      newsletter_subscription = NewsletterSubscription.create! valid_attributes
      get edit_admins_newsletter_subscription_url(newsletter_subscription)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new NewsletterSubscription" do
        expect {
          post admins_newsletter_subscriptions_url, params: { newsletter_subscription: valid_attributes }
        }.to change(NewsletterSubscription, :count).by(1)
      end

      it "redirects to the created newsletter_subscription" do
        post admins_newsletter_subscriptions_url, params: { newsletter_subscription: valid_attributes }
        expect(response).to redirect_to(admins_newsletter_subscription_url(NewsletterSubscription.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new NewsletterSubscription" do
        expect {
          post admins_newsletter_subscriptions_url, params: { newsletter_subscription: invalid_attributes }
        }.to change(NewsletterSubscription, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admins_newsletter_subscriptions_url, params: { newsletter_subscription: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested newsletter_subscription" do
        newsletter_subscription = NewsletterSubscription.create! valid_attributes
        patch admins_newsletter_subscription_url(newsletter_subscription), params: { newsletter_subscription: new_attributes }
        newsletter_subscription.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the newsletter_subscription" do
        newsletter_subscription = NewsletterSubscription.create! valid_attributes
        patch admins_newsletter_subscription_url(newsletter_subscription), params: { newsletter_subscription: new_attributes }
        newsletter_subscription.reload
        expect(response).to redirect_to(newsletter_subscription_url(newsletter_subscription))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        newsletter_subscription = NewsletterSubscription.create! valid_attributes
        patch admins_newsletter_subscription_url(newsletter_subscription), params: { newsletter_subscription: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested newsletter_subscription" do
      newsletter_subscription = NewsletterSubscription.create! valid_attributes
      expect {
        delete admins_newsletter_subscription_url(newsletter_subscription)
      }.to change(NewsletterSubscription, :count).by(-1)
    end

    it "redirects to the newsletter_subscriptions list" do
      newsletter_subscription = NewsletterSubscription.create! valid_attributes
      delete admins_newsletter_subscription_url(newsletter_subscription)
      expect(response).to redirect_to(admins_newsletter_subscriptions_url)
    end
  end
end
